# frozen_string_literal: true

namespace :tailwindcss do
  desc "Write Bundler gem @source paths for the dummy Tailwind build"
  task gem_sources: :environment do
    gems = {
      "flat_pack" => [
        "app/components/**/*.rb",
        "app/components/**/*.erb"
      ],
      "recording_studio" => ["app/views/**/*.erb"],
      "recording_studio_internationalization" => ["app/views/**/*.erb"]
    }

    lines = ["/* Auto-generated by rake tailwindcss:gem_sources. Do not edit. */", ""]

    gems.each do |name, globs|
      spec = Gem.loaded_specs[name]
      next unless spec

      globs.each do |glob|
        lines << %(@source "#{spec.full_gem_path}/#{glob}";)
      end
    end

    output = Rails.root.join("app/assets/builds/tailwind/gem_sources.css")
    FileUtils.mkdir_p(output.dirname)
    File.write(output, "#{lines.join("\n")}\n")
  end
end

if Rake::Task.task_defined?("tailwindcss:build")
  Rake::Task["tailwindcss:build"].enhance(["tailwindcss:gem_sources"])
end

if Rake::Task.task_defined?("tailwindcss:watch")
  Rake::Task["tailwindcss:watch"].enhance(["tailwindcss:gem_sources"])
end
